### ISSUE TITLE
Consider supporting gRPC only

### ISSUE THREAD

**Issue by roji** [neon-sunset/Pinecone.NET#112]
I see the driver has support for both gRPC and REST, and am wondering if there's a particular reason for that - why would a user choose to use REST over gRPC (e.g. is there functionality that's only available via REST)? I've seen this as a pattern in other vector database SDKs, and in many cases it's possible to support gRPC-only, simplifying the SDK and removing another unneeded decision point for the user.

(this is something that can/should be checked with Pinecone themselves, based on their plans etc.)

**Comment by neon-sunset** [comment]
Hello Shay,

Given Pinecone has been providing support for both, I see no reason not to do the same, especially since it's easy to do so with C#. Unfortunately, the guidance on which one to use from Pinecone's side is very limited.

Pinecone themselves use REST transport with TS and Python (as a default) instead of gRPC, with the latter suggested as performance optimization[^1]. Indeed, at the time of initial implementation, my tests showed gRPC to have better upsert and query throughput, but at, sometimes, greater allocation traffic as current gRPC tooling leaves performance on the table (though it is *overall* more efficient since there is no need to pay for expensive `float` to text formatting and parsing).

However, it is also not possible to (easily) use gRPC in some environments which might be doing e.g. TLS termination for outgoing connection on the hosts, proxying it, which breaks HTTP/2 unless the solution explicitly supports it. Or there might be other reasons for HTTP/2-related issues. Example: https://github.com/neon-sunset/Pinecone.NET/issues/93

So far, just exposing non-generic `pincone.GetIndex(name)` that defaults to gRPC has been enough to guide the users towards this choice, with escape hatch available should they need it.

[^1]: https://docs.pinecone.io/guides/data/upsert-data#grpc-python-client

**Comment by neon-sunset** [comment]
@roji Thank you for submitting the issue. I will close it for the time being as the question has been answered, but feel free to comment should you have any concerns.
