### ISSUE TITLE
Dependence on preview versions of System.Text and System.Net.Http.Json

### ISSUE THREAD

**Issue by rdorris** [neon-sunset/Pinecone.NET#23]
Hello and thanks for the pinecone.net package. Works really well in my testing, however, the dependencies on preview versions of code is preventing me from going live. Is there any thought to releasing a version using released versions? Can I assume v8.0.0 had some features that made it much easier to code?
Thanks.

**Comment by neon-sunset** [comment]
Hi @rdorris.
I had to take dependency on preview version of `System.Text.Json` because support for source-generated serialization of `required` properties has only been added in .NET 8 which is scheduled for release in November.

This was motivated by the fact that using `required` property makes implementation much cleaner and with `WarningsAsErrors: Nullable` finally aligns actual behavior with type system representation.

Since older targets are forward-compatible with newer packages, the only issue here is it is a preview version package. It otherwise does not have any major bugs that affect this library.

I will check if there is any polyfill that allows prior `System.Text.Json` versions to be compatible with `required` and update if possible, but otherwise there is little reason to do so.

For additional reliability, I suggest using indexes via `GrpcTransport` because Protobuf preserves byte representation of floating point values while JSON serialization forces them to be formatted as UTF-8 characters which can introduce side-effects due to rounding or specifics of serializers (both on the end of this library and Pinecone).

**Comment by neon-sunset** [comment]
I'm going to close this issue for now but if you have any questions/concerns - feel free to reopen it or submit a new one.
