### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by etynosa** [neon-sunset/Pinecone.NET#91]
When attempting to retrieve the index using the GetIndex method by providing the indexName of a serverless index, an HttpRequestException is encountered. The exception message is as follows: `System.Net.Http.HttpRequestException: 'Response status code does not indicate success: 404 (Not Found).'`

Steps to Reproduce:
Call the GetIndex method on a serverless index using the corresponding indexName.
Observe the raised HttpRequestException with the mentioned status code (404).

**Comment by neon-sunset** [comment]
Right, I was expecting something like this happening sooner or later. Thank you for submitting the issue.

There seem to be other changes to the index management API - I'm going to integrate them too, expect a release soon.

**Comment by neon-sunset** [comment]
Hi @AlexPlom If you would like to contribute, a good place to start is to go through each request at https://docs.pinecone.io/reference (thankfully the API is still very simple) and see how it differs with the current model defined in this project. This is what I did for e.g. 1.4.0 release when noticing previous API changes. The caveat here is it seems Serverless API has more differences and I quickly realized it will take more time to figure out if the differences are backwards compatible and/or need additional handling.

Unfortunately, it appears that Pinecone have stopped serving OpenAPI spec file to their frontend which I'd probably use in this case given there are more changes this time, so the manual approach it is. Alternatively, you could look for the spec file in Pinecone's libraries but quick search did not turn up with anything useful. Because of these aspects and the fact that testing Serverless needs switching to paid plan if you already have pod-based index, I realized it will take more time than I'm willing to allocate to this project at this moment.

Overall, the reason this library exists in the first place is that manually writing it was a faster option to guarantee good and reliable client impl. that properly glues together REST control plane API and gRPC data one, and works well with C# - NSwag, Kiota and other client generators are terrible, produce AOT-incompatible code and pick bad containers for data where it matters.

In order to get started, you only need latest .NET SDK and that's it. I'd be happy to review a PR and assist with getting it merged if you're interested.

Let me know if you have any questions.

**Comment by neon-sunset** [comment]
Serverless is now supported with the version 2.0: https://github.com/neon-sunset/Pinecone.NET/releases/tag/2.0.0
